# 🗑️ Drop Existing Objects (Safe Reset)

DROP TABLE transactions_KNBtbl CASCADE CONSTRAINTS;
DROP TABLE accounts_KNBtbl CASCADE CONSTRAINTS;
DROP TABLE users_KNBtbl CASCADE CONSTRAINTS;
DROP TABLE audit_log_KNBtbl CASCADE CONSTRAINTS;
DROP SEQUENCE acno_seq_KNBtbl;

# ⚙️ Recreate Schema

-- USERS TABLE: stores staff, managers, clients
CREATE TABLE users_KNBtbl (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(200) NOT NULL,
    name VARCHAR2(100),
    email VARCHAR2(100),
    mobile VARCHAR2(20),
    role VARCHAR2(20) NOT NULL CHECK (role IN ('admin', 'manager', 'client')),
    status VARCHAR2(20) DEFAULT 'ACTIVE'
);

-- ACCOUNTS TABLE
CREATE TABLE accounts_KNBtbl (
    acno NUMBER(12) PRIMARY KEY,
    user_id NUMBER UNIQUE,
    name VARCHAR2(100) NOT NULL,
    balance NUMBER(15,2) NOT NULL,
    mobile_number VARCHAR2(20),
    account_type VARCHAR2(20) DEFAULT 'SAVINGS',
    account_status VARCHAR2(20) DEFAULT 'ACTIVE',
    FOREIGN KEY (user_id) REFERENCES users_KNBtbl(user_id)
);

-- TRANSACTIONS TABLE
CREATE TABLE transactions_KNBtbl (
    tx_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    acno NUMBER(12),
    type VARCHAR2(20) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    from_acno NUMBER(12),
    to_acno NUMBER(12),
    date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'SUCCESS',
    remarks VARCHAR2(255),
    FOREIGN KEY (acno) REFERENCES accounts_KNBtbl(acno)
);

-- AUDIT LOG FOR ADMIN ACTIONS
CREATE TABLE audit_log_KNBtbl (
    audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    action VARCHAR2(100),
    action_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    details VARCHAR2(500)
);

-- ACCOUNT NUMBER SEQUENCE
CREATE SEQUENCE acno_seq_KNBtbl START WITH 10000 INCREMENT BY 1;

# 👤 Insert Default Users

INSERT INTO users_KNBtbl (username, password, name, role) 
VALUES ('Prak', 'prak05', 'Prak', 'admin');

INSERT INTO users_KNBtbl (username, password, name, role) 
VALUES ('AdithyaBaiju', 'adi05', 'Adithya Baiju', 'manager');

# 💳 Insert Example Client (for Client Dashboard testing)

INSERT INTO users_KNBtbl (username, password, name, email, mobile, role) 
VALUES ('client01', 'cli05', 'Prakhar Sharma', 'prakhar@mail.com', '9876543210', 'client');

INSERT INTO accounts_KNBtbl (acno, user_id, name, balance, mobile_number, account_type, account_status)
VALUES (acno_seq_KNBtbl.NEXTVAL, 
        (SELECT user_id FROM users_KNBtbl WHERE username='client01'), 
        'Prakhar Sharma', 
        5000.00, 
        '9876543210', 
        'SAVINGS', 
        'ACTIVE');

COMMIT;

